version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    env_file:
      - ./backend/.env
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - REACT_APP_BACKEND_URL='http://192.168.29.113:4003'